name: dgis_maps_flutter_ios
description: iOS implementation of the google_maps_flutter plugin.
repository: https://github.com/flown-pro/dgis_maps_flutter/tree/main/dgis_maps_flutter_ios
homepage: https://github.com/flown-pro/dgis_maps_flutter/tree/main
version: 0.0.1

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter
  dgis_maps_flutter_platform_interface:
    path: ../dgis_maps_flutter_platform_interface
    # git: 
    #   url: https://github.com/flown-pro/dgis_maps_flutter.git
    #   path: dgis_maps_flutter_platform_interface
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
    
flutter:
  plugin:
    platforms:
      ios:
        pluginClass: DgisMapsFlutterIosPlugin
