name: dgis_maps_flutter_android
description: Android implementation of the dgis_maps_flutter plugin.
repository: https://github.com/flown-pro/dgis_maps_flutter/tree/main/dgis_maps_flutter_android
homepage: https://github.com/flown-pro/dgis_maps_flutter
version: 0.0.1

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  dgis_maps_flutter_platform_interface:
    git: 
      url: https://github.com/flown-pro/dgis_maps_flutter.git
      path: dgis_maps_flutter_platform_interface
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: pro.flown.dgis_maps_flutter_android
        pluginClass: DgisMapsFlutterAndroidPlugin