name: dgis_maps_flutter_platform_interface
description:  A common platform interface for the dgis_maps_flutter plugin.
repository: https://github.com/flown-pro/dgis_maps_flutter/tree/main/dgis_maps_flutter_platform_interface
homepage: https://github.com/flown-pro/dgis_maps_flutter
version: 0.0.1

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
