name: dgis_maps_flutter
publish_to: "none"
description: A Flutter plugin for integrating 2GIS Maps in iOS and Android applications.
repository: https://github.com/flown-pro/dgis_maps_flutter/tree/main/dgis_maps_flutter
homepage: https://github.com/flown-pro/dgis_maps_flutter
version: 0.0.1

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  dgis_maps_flutter_android:
    path: ../dgis_maps_flutter_android
    # git: 
    #   url: https://github.com/flown-pro/dgis_maps_flutter.git
    #   path: dgis_maps_flutter_android
  dgis_maps_flutter_ios: 
    path: ../dgis_maps_flutter_ios
    # git: 
    #   url: https://github.com/flown-pro/dgis_maps_flutter.git
    #   path: dgis_maps_flutter_ios
  dgis_maps_flutter_platform_interface:
    path: ../dgis_maps_flutter_platform_interface
    # git: 
    #   url: https://github.com/flown-pro/dgis_maps_flutter.git
    #   path: dgis_maps_flutter_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        default_package: dgis_maps_flutter_android
      ios:
        default_package: dgis_maps_flutter_ios
